const { stripIndents, oneLine } = require('common-tags');
const { MessageEmbed } = require('discord.js');
const Commando, { Client } = require('discord.js-commando');
const { disambigation } = Commando.util;

module.exports = class HelpCommand extends Command {
	constructor(client) {
		super(client, {
			name: 'help',
			group: 'util',
			memberName: 'help',
			aliases: ['commands'],
			description: 'Displays a list of available commands, or detailed information for a specified command.',
			details: oneLine`
				The command may be part of a command name or a whole command name.
				If it isn't specified, all available commands will be listed.
			`,
			examples: ['help', 'help prefix'],
			guarded: true,

			args: [
				{
					key: 'command',
					prompt: 'Which command would you like to view the help for?',
					type: 'string',
					default: ''
				}
			]
		});
	}

	async run(msg, args) {
		const groups = this.client.registry.groups;
		const commands = this.client.registry.findCommands(args.command, false, msg);
		const messages = []

		commands.map(command => {
			let embed = new MessageEmbed()
				.setColor('#0099ff')
				.setTitle('uberbot Help')
				.setURL('https://uberbot.xyz/')
				.setAuthor('uberbot', 'https://images.discordapp.net/avatars/354358007376642048/0c28f93f4ab3abbf10b9aa700b8cfc65.png?size=128', 'https://uberbot.xyz/')
				.addField('Name', `${command.name}${command.guildOnly ? ' (Only usable in servers)' : '' }${command.nsfw ? ' (NSFW)' : ''}`)
			if (command.aliases && command.aliases.length > 0) embed.addField('Aliases', command.aliases.join(', '));
			if (command.details) embed.addField('Details', command.details);
			if (command.examples) embed.addField('Examples', command.examples.join('\n'));
				
			embed
				.setTimestamp()
				.setFooter(`Message autogenerated by uberbot, dm ${this.client.owners[0].user.tag}`)

			)

			messages.push(embed);
		});

		if (msg.channel.type !== 'dm') msg.reply('Sent you a DM with information.');
		return await msg.direct ({ embeds: messages });
	}
};
